#
#CONFIG OPTIONS
#
#	allowUnicodeIdentifiers
#	    boolean, toggles whether unicode identifiers are allowed in names or not, default is false (Default: false)
#
#	disallowAdditionalPropertiesIfNotPresent
#	    If false, the 'additionalProperties' implementation (set to true by default) is compliant with the OAS and JSON schema specifications. If true (default), keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default. (Default: true)
#	        false - The 'additionalProperties' implementation is compliant with the OAS and JSON schema specifications.
#	        true - Keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default.
#
#	ensureUniqueParams
#	    Whether to ensure parameter names are unique in an operation (rename parameters that are not). (Default: true)
#
#	enumNameSuffix
#	    Suffix that will be appended to all enum names. (Default: Enum)
#
#	enumPropertyNaming
#	    Naming convention for enum properties: 'camelCase', 'PascalCase', 'snake_case', 'UPPERCASE', and 'original' (Default: PascalCase)
#
#	legacyDiscriminatorBehavior
#	    Set to false for generators with better support for discriminators. (Python, Java, Go, PowerShell, C#have this enabled by default). (Default: true)
#	        true - The mapping in the discriminator includes descendent schemas that allOf inherit from self and the discriminator mapping schemas in the OAS document.
#	        false - The mapping in the discriminator includes any descendent schemas that allOf inherit from self, any oneOf schemas, any anyOf schemas, any x-discriminator-values, and the discriminator mapping schemas in the OAS document AND Codegen validates that oneOf and anyOf schemas contain the required discriminator and throws an error if the discriminator is missing.
#
#	modelPropertyNaming
#	    Naming convention for the property: 'camelCase', 'PascalCase', 'snake_case' and 'original', which keeps the original name. Only change it if you provide your own run-time code for (de-)serialization of models (Default: original)
#
#	npmName
#	    The name under which you want to publish generated npm package. Required to generate a full package
#
#	npmRepository
#	    Use this property to set an url of your private npmRepo in the package.json
#
#	npmVersion
#	    The version of your npm package. If not provided, using the version from the OpenAPI specification file. (Default: 1.0.0)
#
#	nullSafeAdditionalProps
#	    Set to make additional properties types declare that their indexer may return undefined (Default: false)
#
#	prependFormOrBodyParameters
#	    Add form or body parameters to the beginning of the parameter list. (Default: false)
#
#	snapshot
#	    When setting this property to true, the version will be suffixed with -SNAPSHOT.yyyyMMddHHmm (Default: false)
#
#	sortModelPropertiesByRequiredFlag
#	    Sort model properties to place required parameters before optional parameters. (Default: true)
#
#	sortParamsByRequiredFlag
#	    Sort method arguments to place required parameters before optional parameters. (Default: true)
#
supportsES6: true
#	    Generate code that conforms to ES6. (Default: false)
#
#	useSingleRequestParameter
#	    Setting this property to true will generate functions with a single argument containing all API endpoint parameters instead of one argument per parameter. (Default: false)
#
#	withInterfaces
#	    Setting this property to true will generate interfaces next to the default class implementations. (Default: false)
#
#	withSeparateModelsAndApi
#	    Put the model and api in separate folders and in separate classes (Default: false)
#
#	withoutPrefixEnums
#	    Don't prefix enum names with class names (Default: false)
#
